<?php
declare(strict_types=1);

namespace Panth\RobotsSeo\Setup\Patch\Data;

use Magento\Framework\App\ResourceConnection;
use Magento\Framework\Setup\Patch\DataPatchInterface;
use Magento\Store\Model\StoreManagerInterface;

/**
 * Installs one `url_rewrite` row per store view so `/robots.txt` resolves to
 * our frontend controller (`seo_robots/robots/index`). Inserts are idempotent:
 * the same row is skipped on rerun by the composite unique key on
 * (store_id, request_path).
 *
 * The Magento_Robots core router is disabled in `etc/frontend/di.xml` so the
 * URL rewrite row installed here actually wins the route resolution.
 */
class InstallRobotsTxtRewrite implements DataPatchInterface
{
    private const REQUEST_PATH = 'robots.txt';
    private const TARGET_PATH  = 'seo_robots/robots/index';

    public function __construct(
        private readonly ResourceConnection $resource,
        private readonly StoreManagerInterface $storeManager
    ) {
    }

    public function apply(): self
    {
        $connection = $this->resource->getConnection();
        $table = $this->resource->getTableName('url_rewrite');
        if (!$connection->isTableExists($table)) {
            return $this;
        }

        foreach ($this->storeManager->getStores(true) as $store) {
            $storeId = (int) $store->getId();
            $exists = (int) $connection->fetchOne(
                $connection->select()
                    ->from($table, 'COUNT(*)')
                    ->where('store_id = ?', $storeId)
                    ->where('request_path = ?', self::REQUEST_PATH)
            );
            if ($exists > 0) {
                continue;
            }
            $connection->insert($table, [
                'entity_type'      => 'custom',
                'entity_id'        => 0,
                'request_path'     => self::REQUEST_PATH,
                'target_path'      => self::TARGET_PATH,
                'redirect_type'    => 0,
                'store_id'         => $storeId,
                'description'      => 'Panth_RobotsSeo dynamic robots.txt',
                'is_autogenerated' => 1,
                'metadata'         => null,
            ]);
        }

        return $this;
    }

    public static function getDependencies(): array
    {
        return [InstallDefaultRobotsPolicy::class];
    }

    public function getAliases(): array
    {
        return [];
    }
}
