<?php
declare(strict_types=1);

namespace Panth\RobotsSeo\Model\Robots;

use Magento\Framework\App\Filesystem\DirectoryList;
use Magento\Framework\App\ResourceConnection;
use Magento\Framework\Filesystem;
use Magento\Framework\Filesystem\Directory\ReadInterface;
use Magento\Framework\UrlInterface;
use Magento\Store\Model\StoreManagerInterface;
use Panth\RobotsSeo\Api\RobotsPolicyInterface;
use Panth\RobotsSeo\Helper\Config;
use Panth\RobotsSeo\Service\DirectiveValidator;

class PolicyResolver implements RobotsPolicyInterface
{
    public const LLM_BOT_CONFIG_MAP = [
        'GPTBot'             => 'gptbot',
        'ChatGPT-User'       => 'chatgpt_user',
        'OAI-SearchBot'      => 'oai_searchbot',
        'ClaudeBot'          => 'claudebot',
        'Claude-Web'         => 'claudebot',
        'anthropic-ai'       => 'anthropic_ai',
        'Google-Extended'    => 'google_extended',
        'GoogleOther'        => 'google_extended',
        'CCBot'              => 'ccbot',
        'PerplexityBot'      => 'perplexitybot',
        'cohere-ai'          => 'cohere_ai',
        'Bytespider'         => 'bytespider',
        'Amazonbot'          => 'amazonbot',
        'Applebot-Extended'  => 'applebot_extended',
        'FacebookBot'        => 'facebookbot',
        'meta-externalagent' => 'meta_externalagent',
        'YouBot'             => null,
        'PetalBot'           => null,
        'Diffbot'            => null,
        'AI2Bot'             => null,
        'Omgilibot'          => null,
        'Timpibot'           => null,
    ];

    private const SITEMAP_FILENAME_PATTERN = '/^[A-Za-z0-9][A-Za-z0-9_-]*(?:\.[A-Za-z0-9_-]+)*\.xml$/';

    public const LLM_BOTS = [
        'GPTBot', 'ChatGPT-User', 'OAI-SearchBot', 'ClaudeBot', 'Claude-Web',
        'anthropic-ai', 'Google-Extended', 'GoogleOther', 'CCBot',
        'PerplexityBot', 'cohere-ai', 'Bytespider', 'Amazonbot',
        'Applebot-Extended', 'FacebookBot', 'meta-externalagent',
        'YouBot', 'PetalBot', 'Diffbot', 'AI2Bot', 'Omgilibot', 'Timpibot',
    ];

    public function __construct(
        private readonly ResourceConnection $resource,
        private readonly StoreManagerInterface $storeManager,
        private readonly Config $config,
        private readonly MetaResolver $metaResolver,
        private readonly DirectiveValidator $validator,
        private readonly Filesystem $filesystem
    ) {
    }

    public function getMetaRobots(string $entityType, int $entityId, int $storeId): string
    {
        return $this->metaResolver->resolveWithDirectives($entityType, $entityId, $storeId);
    }

    public function getHeaderRobots(string $entityType, int $entityId, int $storeId): string
    {
        return $this->metaResolver->resolve($entityType, $entityId, $storeId);
    }

    public function getRobotsTxt(int $storeId): string
    {
        if ($this->config->isRobotsTxtOverrideEnabled($storeId)) {
            $custom = $this->config->getCustomRobotsTxt($storeId);
            if (trim($custom) !== '') {
                return $this->normalizeBody($custom);
            }
        }

        $lines = [];
        $lines[] = '# Generated by Panth_RobotsSeo for store ' . $storeId;
        $lines[] = '# ' . gmdate('Y-m-d H:i:s') . ' UTC';
        $lines[] = '';

        $rows = $this->loadPolicyRows($storeId);
        $groups = [];
        $llmRows = [];
        $llmNames = array_map('strtolower', self::LLM_BOTS);
        foreach ($rows as $row) {
            $ua = trim((string) ($row['user_agent'] ?? ''));
            $ua = $ua !== '' ? $ua : '*';

            if ($ua !== '*' && !$this->validator->isValidUserAgent($ua)) {
                continue;
            }
            if (in_array(strtolower($ua), $llmNames, true)) {
                $llmRows[strtolower($ua)][] = $row;
                continue;
            }
            $groups[$ua][] = $row;
        }
        if (!isset($groups['*'])) {
            $groups['*'] = [];
        }

        foreach ($this->getLlmBotPolicy($storeId) as $ua => $allowed) {
            if (!$this->validator->isValidUserAgent($ua)) {
                continue;
            }
            $lines[] = 'User-agent: ' . $ua;
            $ruleLines = [];
            if ($allowed) {
                foreach ($llmRows[strtolower($ua)] ?? [] as $entry) {
                    $ruleLine = $this->formatRule($entry);
                    if ($ruleLine !== null) {
                        $ruleLines[$ruleLine] = $ruleLine;
                    }
                }
            }
            if ($ruleLines === []) {
                $ruleLines[] = $allowed ? 'Allow: /' : 'Disallow: /';
            }
            foreach ($ruleLines as $ruleLine) {
                $lines[] = $ruleLine;
            }
            $lines[] = '';
        }

        foreach ($groups as $ua => $entries) {
            $lines[] = 'User-agent: ' . $ua;
            if ($entries === [] && $ua === '*') {
                foreach ($this->getDefaultDisallows() as $path) {
                    $lines[] = 'Disallow: ' . $path;
                }
            } else {
                foreach ($entries as $entry) {
                    $ruleLine = $this->formatRule($entry);
                    if ($ruleLine !== null) {
                        $lines[] = $ruleLine;
                    }
                }
            }
            if ($ua === '*') {
                $crawlDelay = $this->config->getCrawlDelay($storeId);
                if ($crawlDelay > 0) {
                    $lines[] = 'Crawl-delay: ' . $crawlDelay;
                }
            }
            $lines[] = '';
        }

        try {
            $host = $this->getStoreHost($storeId);
            $store = $this->storeManager->getStore($storeId);
            $baseUrl = rtrim($store->getBaseUrl(), '/');
            foreach ($this->resolveSitemapLines($storeId, $baseUrl) as $sitemapLine) {
                $lines[] = $sitemapLine;
            }
            if ($host !== '') {
                $lines[] = 'Host: ' . $host;
            }
        } catch (\Throwable) {
        }

        return implode("\n", $lines) . "\n";
    }

    public function getLlmBotPolicy(int $storeId): array
    {
        $out = [];
        foreach (self::LLM_BOT_CONFIG_MAP as $ua => $configKey) {
            if ($configKey === null) {
                $out[$ua] = true;
                continue;
            }
            $out[$ua] = $this->config->isLlmBotAllowed($configKey, $storeId);
        }
        return $out;
    }

    private function loadPolicyRows(int $storeId): array
    {
        $connection = $this->resource->getConnection();
        $table = $this->resource->getTableName('panth_seo_robots_policy');
        if (!$connection->isTableExists($table)) {
            return [];
        }
        $select = $connection->select()
            ->from($table)
            ->where('store_id IN (?)', [0, $storeId])
            ->where('is_active = ?', 1)
            ->order('priority ASC');
        return $connection->fetchAll($select);
    }

    private function getDefaultDisallows(): array
    {
        return [
            '/index.php/',
            '/catalog/product_compare/',
            '/catalog/category/view/',
            '/catalog/product/view/',
            '/catalogsearch/',
            '/checkout/',
            '/customer/',
            '/customer/account/',
            '/customer/account/login/',
            '/newsletter/subscriber/new/',
            '/review/product/',
            '/sendfriend/',
            '/wishlist/',
            '/*?SID=',
            '/*?___store=',
            '/*?p=*&product_list_order=',
            '/*?product_list_dir=',
            '/*?product_list_limit=',
            '/*?product_list_mode=',
        ];
    }

    private function formatRule(array $entry): ?string
    {
        $directive = strtolower((string) ($entry['directive'] ?? '')) === 'disallow'
            ? 'Disallow'
            : 'Allow';
        $path = trim((string) ($entry['path'] ?? '/'));
        if (!$this->validator->isValidPath($path)) {
            return null;
        }
        return $directive . ': ' . $path;
    }

    private function resolveSitemapLines(int $storeId, string $baseUrl): array
    {
        $lines = [];
        foreach ($this->config->getSitemapUrls($storeId) as $value) {
            $url = str_replace('{{base_url}}', $baseUrl, $value);
            if (str_starts_with($url, '/')) {
                $url = $baseUrl . $url;
            }
            if (preg_match('#^https?://#i', $url) !== 1) {
                continue;
            }
            $url = (string) preg_replace('#(?<!:)//+#', '/', $url);
            $line = 'Sitemap: ' . $url;
            $lines[$line] = $line;
        }

        if ($lines === []) {
            foreach ($this->discoverSitemapUrls($storeId) as $url) {
                $line = 'Sitemap: ' . $url;
                $lines[$line] = $line;
            }
        }

        return array_values($lines);
    }

    private function discoverSitemapUrls(int $storeId): array
    {
        $store = $this->storeManager->getStore($storeId);
        $webBase = rtrim((string) $store->getBaseUrl(UrlInterface::URL_TYPE_WEB), '/');
        $pub = $this->filesystem->getDirectoryRead(DirectoryList::PUB);

        $candidates = $this->loadXmlSitemapFiles($storeId, (string) $store->getCode());
        $urls = $this->existingFileUrls($candidates, $pub, $webBase);
        if ($urls !== []) {
            return $urls;
        }

        return $this->existingFileUrls($this->loadMagentoSitemapFiles($storeId), $pub, $webBase);
    }

    private function existingFileUrls(array $relativePaths, ReadInterface $pub, string $webBase): array
    {
        $urls = [];
        foreach ($relativePaths as $relative) {
            try {
                if ($pub->isFile($relative)) {
                    $urls[] = $webBase . '/' . $relative;
                }
            } catch (\Throwable) {
                continue;
            }
        }
        return array_values(array_unique($urls));
    }

    private function loadXmlSitemapFiles(int $storeId, string $storeCode): array
    {
        if (!$this->config->isXmlSitemapEnabled($storeId)) {
            return [];
        }
        $connection = $this->resource->getConnection();
        $table = $this->resource->getTableName('panth_seo_sitemap_profile');
        if (!$connection->isTableExists($table)) {
            return [];
        }
        $columns = ['output_path'];
        if ($connection->tableColumnExists($table, 'sitemap_filename')) {
            $columns[] = 'sitemap_filename';
        }
        $select = $connection->select()
            ->from($table, $columns)
            ->where('store_id = ?', $storeId)
            ->where('is_active = ?', 1)
            ->order('profile_id ASC');

        $fallback = $this->config->getXmlSitemapIndexFilename($storeId);
        $files = [];
        foreach ($connection->fetchAll($select) as $row) {
            $dir = $this->normaliseRelativeDir((string) ($row['output_path'] ?? ''), $storeCode);
            $filename = trim((string) ($row['sitemap_filename'] ?? ''));
            if ($filename === '' || preg_match(self::SITEMAP_FILENAME_PATTERN, $filename) !== 1) {
                $filename = $fallback;
            }
            $files[] = ($dir === '' ? '' : $dir . '/') . $filename;
        }
        return $files;
    }

    private function loadMagentoSitemapFiles(int $storeId): array
    {
        $connection = $this->resource->getConnection();
        $table = $this->resource->getTableName('sitemap');
        if (!$connection->isTableExists($table)) {
            return [];
        }
        $select = $connection->select()
            ->from($table, ['sitemap_path', 'sitemap_filename'])
            ->where('store_id = ?', $storeId)
            ->order('sitemap_id ASC');

        $files = [];
        foreach ($connection->fetchAll($select) as $row) {
            $filename = basename(trim((string) ($row['sitemap_filename'] ?? '')));
            if ($filename === '' || preg_match('/^[A-Za-z0-9._-]+$/', $filename) !== 1) {
                continue;
            }
            $dir = $this->normaliseRelativeDir((string) ($row['sitemap_path'] ?? ''), '', false);
            $files[] = ($dir === '' ? '' : $dir . '/') . $filename;
        }
        return $files;
    }

    private function normaliseRelativeDir(string $path, string $storeCode, bool $xmlSitemapDefault = true): string
    {
        $path = trim($path);
        if ($path === '' && $xmlSitemapDefault) {
            $path = 'xmlsitemap/{store_code}/';
        }
        $path = strtr($path, ['{store_code}' => $storeCode]);

        $segments = [];
        foreach (explode('/', str_replace('\\', '/', $path)) as $segment) {
            $segment = trim($segment);
            if ($segment === '' || $segment === '.') {
                continue;
            }
            if ($segment === '..' || preg_match('/^[A-Za-z0-9._-]+$/', $segment) !== 1) {
                return $xmlSitemapDefault ? 'xmlsitemap/' . $storeCode : '';
            }
            $segments[] = $segment;
        }
        return implode('/', $segments);
    }

    private function getStoreHost(int $storeId): string
    {
        try {
            $base = (string) $this->storeManager->getStore($storeId)->getBaseUrl();
            $host = parse_url($base, PHP_URL_HOST);
            return is_string($host) ? $host : '';
        } catch (\Throwable) {
            return '';
        }
    }

    private function normalizeBody(string $body): string
    {
        $body = str_replace(["\0", "\r\n", "\r"], ['', "\n", "\n"], $body);
        if ($body === '' || !str_ends_with($body, "\n")) {
            $body .= "\n";
        }
        return $body;
    }
}
