<?php
declare(strict_types=1);

namespace Panth\RobotsSeo\Model\Robots;

use Magento\Framework\App\ResourceConnection;
use Magento\Store\Model\StoreManagerInterface;
use Panth\RobotsSeo\Api\RobotsPolicyInterface;
use Panth\RobotsSeo\Helper\Config;
use Panth\RobotsSeo\Service\DirectiveValidator;

/**
 * Aggregates per-store `panth_seo_robots_policy` rows + LLM bot toggles from
 * system.xml + a Sitemap: line into a single robots.txt body.
 *
 * Also satisfies the meta / X-Robots-Tag resolvers by delegating to
 * `MetaResolver` so that external callers that only know about
 * RobotsPolicyInterface get a consistent answer.
 *
 * SECURITY: every row coming out of the DB is re-validated before it is
 * echoed into the robots.txt body. Even though `Controller\Adminhtml\Policy\Save`
 * rejects malformed input at save-time, a defence-in-depth validation here
 * protects against tampering via direct SQL or a broken migration.
 */
class PolicyResolver implements RobotsPolicyInterface
{
    /**
     * Known LLM crawler user agents mapped to the system.xml field id that
     * governs their allow/disallow flag. The key is the exact `User-agent:`
     * string that appears in robots.txt; the value is the snake_case field id
     * declared under `panth_robots_seo/llm_bots/*` in system.xml / config.xml.
     *
     * @var array<string,?string>
     */
    public const LLM_BOT_CONFIG_MAP = [
        'GPTBot'             => 'gptbot',
        'ChatGPT-User'       => 'chatgpt_user',
        'OAI-SearchBot'      => 'oai_searchbot',
        'ClaudeBot'          => 'claudebot',
        'Claude-Web'         => 'claudebot',
        'anthropic-ai'       => 'anthropic_ai',
        'Google-Extended'    => 'google_extended',
        'GoogleOther'        => 'google_extended',
        'CCBot'              => 'ccbot',
        'PerplexityBot'      => 'perplexitybot',
        'cohere-ai'          => 'cohere_ai',
        'Bytespider'         => 'bytespider',
        'Amazonbot'          => 'amazonbot',
        'Applebot-Extended'  => 'applebot_extended',
        'FacebookBot'        => 'facebookbot',
        'meta-externalagent' => 'meta_externalagent',
        'YouBot'             => null,
        'PetalBot'           => null,
        'Diffbot'            => null,
        'AI2Bot'             => null,
        'Omgilibot'          => null,
        'Timpibot'           => null,
    ];

    /**
     * Flat list of the UA strings above — kept for callers that need a plain
     * array rather than the config map.
     *
     * @var string[]
     */
    public const LLM_BOTS = [
        'GPTBot', 'ChatGPT-User', 'OAI-SearchBot', 'ClaudeBot', 'Claude-Web',
        'anthropic-ai', 'Google-Extended', 'GoogleOther', 'CCBot',
        'PerplexityBot', 'cohere-ai', 'Bytespider', 'Amazonbot',
        'Applebot-Extended', 'FacebookBot', 'meta-externalagent',
        'YouBot', 'PetalBot', 'Diffbot', 'AI2Bot', 'Omgilibot', 'Timpibot',
    ];

    public function __construct(
        private readonly ResourceConnection $resource,
        private readonly StoreManagerInterface $storeManager,
        private readonly Config $config,
        private readonly MetaResolver $metaResolver,
        private readonly DirectiveValidator $validator
    ) {
    }

    public function getMetaRobots(string $entityType, int $entityId, int $storeId): string
    {
        return $this->metaResolver->resolveWithDirectives($entityType, $entityId, $storeId);
    }

    public function getHeaderRobots(string $entityType, int $entityId, int $storeId): string
    {
        return $this->metaResolver->resolve($entityType, $entityId, $storeId);
    }

    public function getRobotsTxt(int $storeId): string
    {
        // Admin-provided override short-circuits everything. Even though
        // we trust the admin user to not paste malicious content here, we
        // still strip CR/LF injection attempts into the header area by
        // normalising line endings. The body is still served as
        // `text/plain` so XSS is not relevant.
        if ($this->config->isRobotsTxtOverrideEnabled($storeId)) {
            $custom = $this->config->getCustomRobotsTxt($storeId);
            return $this->normalizeBody($custom);
        }

        $lines = [];
        $lines[] = '# Generated by Panth_RobotsSeo for store ' . $storeId;
        $lines[] = '# ' . gmdate('Y-m-d H:i:s') . ' UTC';
        $lines[] = '';

        // LLM bot policy first — explicit Allow/Disallow per UA block.
        foreach ($this->getLlmBotPolicy($storeId) as $ua => $allowed) {
            if (!$this->validator->isValidUserAgent($ua)) {
                continue;
            }
            $lines[] = 'User-agent: ' . $ua;
            $lines[] = $allowed ? 'Allow: /' : 'Disallow: /';
            $lines[] = '';
        }

        // Default User-agent: * block from panth_seo_robots_policy rows.
        $rows = $this->loadPolicyRows($storeId);
        $groups = [];
        foreach ($rows as $row) {
            $ua = (string) ($row['user_agent'] ?? '');
            $ua = $ua !== '' ? $ua : '*';
            // Hard reject any row that fails the UA whitelist. This protects
            // against tampered DB rows containing CRLF or other injection.
            if ($ua !== '*' && !$this->validator->isValidUserAgent($ua)) {
                continue;
            }
            $groups[$ua][] = $row;
        }
        if (!isset($groups['*'])) {
            $groups['*'] = [];
        }

        foreach ($groups as $ua => $entries) {
            // LLM bots already emitted above.
            if (in_array($ua, self::LLM_BOTS, true)) {
                continue;
            }
            $lines[] = 'User-agent: ' . $ua;
            if ($entries === [] && $ua === '*') {
                foreach ($this->getDefaultDisallows() as $path) {
                    $lines[] = 'Disallow: ' . $path;
                }
            } else {
                foreach ($entries as $entry) {
                    $directive = strtolower((string) ($entry['directive'] ?? '')) === 'disallow'
                        ? 'Disallow'
                        : 'Allow';
                    $path = (string) ($entry['path'] ?? '/');
                    if (!$this->validator->isValidPath($path)) {
                        continue;
                    }
                    $lines[] = $directive . ': ' . $path;
                }
            }
            if ($ua === '*') {
                $crawlDelay = $this->config->getCrawlDelay($storeId);
                if ($crawlDelay > 0) {
                    $lines[] = 'Crawl-delay: ' . $crawlDelay;
                }
            }
            $lines[] = '';
        }

        // Sitemap references for every store view sharing the host.
        try {
            $host = $this->getStoreHost($storeId);
            $store = $this->storeManager->getStore($storeId);
            $baseUrl = rtrim($store->getBaseUrl(), '/');
            $lines[] = 'Sitemap: ' . $baseUrl . '/panth-sitemap.xml';
            $lines[] = 'Sitemap: ' . $baseUrl . '/sitemap.xml';
            if ($host !== '') {
                $lines[] = 'Host: ' . $host;
            }
        } catch (\Throwable) {
            // Sitemap references are optional.
        }

        return implode("\n", $lines) . "\n";
    }

    public function getLlmBotPolicy(int $storeId): array
    {
        $out = [];
        foreach (self::LLM_BOT_CONFIG_MAP as $ua => $configKey) {
            if ($configKey === null) {
                // No dedicated toggle — default to allow so we do not silently
                // block bots a merchant never configured.
                $out[$ua] = true;
                continue;
            }
            $out[$ua] = $this->config->isLlmBotAllowed($configKey, $storeId);
        }
        return $out;
    }

    /**
     * @return array<int,array<string,mixed>>
     */
    private function loadPolicyRows(int $storeId): array
    {
        $connection = $this->resource->getConnection();
        $table = $this->resource->getTableName('panth_seo_robots_policy');
        if (!$connection->isTableExists($table)) {
            return [];
        }
        $select = $connection->select()
            ->from($table)
            ->where('store_id IN (?)', [0, $storeId])
            ->where('is_active = ?', 1)
            ->order('priority ASC');
        return $connection->fetchAll($select);
    }

    /**
     * @return string[]
     */
    private function getDefaultDisallows(): array
    {
        return [
            '/index.php/',
            '/catalog/product_compare/',
            '/catalog/category/view/',
            '/catalog/product/view/',
            '/catalogsearch/',
            '/checkout/',
            '/customer/',
            '/customer/account/',
            '/customer/account/login/',
            '/newsletter/subscriber/new/',
            '/review/product/',
            '/sendfriend/',
            '/wishlist/',
            '/*?SID=',
            '/*?___store=',
            '/*?p=*&product_list_order=',
            '/*?product_list_dir=',
            '/*?product_list_limit=',
            '/*?product_list_mode=',
        ];
    }

    private function getStoreHost(int $storeId): string
    {
        try {
            $base = (string) $this->storeManager->getStore($storeId)->getBaseUrl();
            $host = parse_url($base, PHP_URL_HOST);
            return is_string($host) ? $host : '';
        } catch (\Throwable) {
            return '';
        }
    }

    /**
     * Normalise CRLF to LF and strip NUL bytes from admin-entered body. Leaves
     * the rest of the content untouched so the merchant can use any legal
     * robots.txt directive.
     */
    private function normalizeBody(string $body): string
    {
        $body = str_replace(["\0", "\r\n", "\r"], ['', "\n", "\n"], $body);
        if ($body === '' || !str_ends_with($body, "\n")) {
            $body .= "\n";
        }
        return $body;
    }
}
